name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
      
      - name: Install Dependencies
        run: |
          cd app
          flutter pub get
          
      - name: Format
        run: |
          cd app
          dart format --set-exit-if-changed .
          
      - name: Analyze
        run: |
          cd app
          flutter analyze
          
      - name: Run Tests
        run: |
          cd app
          flutter test
